// Package testapp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.5-0.20221217005803-d516da72dfb7 DO NOT EDIT.
package testapp

// V1CreateOrderErrorResponseBody defines model for V1CreateOrderErrorResponseBody.
type V1CreateOrderErrorResponseBody struct {
	// Error Error description
	Error string `json:"error"`
}

// V1CreateOrderRequestBody defines model for V1CreateOrderRequestBody.
type V1CreateOrderRequestBody struct {
	// ItemsCount Amount of items in order
	ItemsCount int `json:"items_count"`
}

// V1CreateOrderSuccessfulResponseBody defines model for V1CreateOrderSuccessfulResponseBody.
type V1CreateOrderSuccessfulResponseBody struct {
	// Packs Pack list in the order
	Packs []V1Pack `json:"packs"`
}

// V1Pack defines model for V1Pack.
type V1Pack struct {
	// Count Amount of packs in order
	Count int `json:"count"`

	// Size Size of the pack, in items
	Size int `json:"size"`
}

// PostV1OrderJSONRequestBody defines body for PostV1Order for application/json ContentType.
type PostV1OrderJSONRequestBody = V1CreateOrderRequestBody
